"""The frontend's TypeScript types are generated from this checked-in
OpenAPI snapshot. If the backend schema drifts, this test fails until the
snapshot is intentionally regenerated and the frontend types are updated:

    python -m agent_reflex.dashboard.export_openapi
"""

import json
from pathlib import Path

SNAPSHOT = Path("frontend/src/types/openapi.json")


def _strip_framework_noise(schema: dict) -> dict:
    """Remove schema keys that only reflect the FastAPI/pydantic version
    rather than surface API changes:
    - `additionalProperties: true` added to every response object by
      pydantic >= 2.11
    - the `ValidationError`/`HTTPValidationError` component schemas and their
      fields (`ctx`, `input`), which are generated by pydantic and unused by
      the frontend types

    Without this, any dep bump in CI (or locally) false-positives the drift
    while the endpoint contract is unchanged.
    """
    if isinstance(schema, dict):
        schema.pop("additionalProperties", None)
        components = schema.get("components", {}).get("schemas")
        if isinstance(components, dict):
            components.pop("ValidationError", None)
            components.pop("HTTPValidationError", None)
        for value in schema.values():
            _strip_framework_noise(value)
    elif isinstance(schema, list):
        for item in schema:
            _strip_framework_noise(item)
    return schema


def test_openapi_schema_matches_frontend_snapshot():
    from fastapi.testclient import TestClient

    from agent_reflex.dashboard.api import app

    client = TestClient(app)
    live = _strip_framework_noise(client.get("/openapi.json").json())

    if not SNAPSHOT.exists():
        raise AssertionError(
            f"missing openapi snapshot at {SNAPSHOT}; run "
            "python -m agent_reflex.dashboard.export_openapi"
        )

    snapshot = _strip_framework_noise(json.loads(SNAPSHOT.read_text()))
    assert live == snapshot, (
        "backend OpenAPI schema drifted from frontend/types/openapi.json; "
        "run python -m agent_reflex.dashboard.export_openapi and update "
        "frontend/src/lib/types.ts to match"
    )
